= Deploy Mission Critical Application Platform (MCAP)
:navtitle: Home

Welcome to this quick course, _Deploy Mission Critical Application Platform (MCAP)_.
This course will help you learn the basic infrastructure required for MCAP and how to deploy nested OpenShift using OpenShift Virtualization.
After completing this course, you will be able to deploy MCAP solution for production environment.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Arvin Amirian
* Ricardo Garcia Cavero
* Sarvesh Pandit
* Ashish Shah
* Annie Purcell.

== Classroom Environment

=== Red Hat Associates

This introductory course has a few, simple hands-on labs. You will use the https://demo.redhat.com/catalog?item=babylon-catalog-prod/equinix-metal.eqx-blank.prod&utm_source=webapp&utm_medium=share-link.ocp4-workshop-rhods-base-aws.prod[Equinix Metal baremetal blank server,window=read-later] catalog item in the Red Hat Demo Platform (RHDP) to run the hands-on exercises in this course.

Update the Catalog link - ##FIX THIS##

When ordering this catalog item in RHDP:

. Select *Practice/Enablement* for the *Activity* field
. Select the nearest or any region in the *Region* field
. Select *n3.xlarge.x86* as the flavor in *Type* field

=== Red Hat Partners

Partners should be able to access the new https://partner.demo.redhat.com[Red Hat Demo Platform for Partners,window=read-later] by logging in with their RHN account credentials. For more information on this you can refer https://content.redhat.com/us/en/product/cross-portfolio-initiatives/rhdp.html#tabs-333fa7ebb9-item-b6fc845e73-tab[about Red Hat Demo Platform (RHDP),window=read-later]

Catalog link - ##FIX THIS##

For partner support - https://connect.redhat.com/en/support[Help and support,window=read-later]

== Prerequisites

For this course, you should have:

* Red Hat Certified Systems Administrator certification or equivalent knowledge of Linux system administration is recommended for all roles.
* https://rol.redhat.com/rol/app/courses/do280-4.14[Red Hat OpenShift Administration II: Configuring a Production Cluster (DO280),window=read-later] or equivalent knowledge on configuring a production Red Hat OpenShift cluster.
* https://rol.redhat.com/rol/app/technical-overview/do016-4.14[Red Hat OpenShift Virtualization (OCP Virt) Technical Overview (DO016),window=read-later]
* https://rol.redhat.com/rol/app/courses/do316-4.14[Managing Virtual Machines with Red Hat OpenShift Virtualization (DO316),window=read-later] or equivalent knowledge on how to create virtual machines on Red Hat OpenShift cluster using Red Hat OpenShift Virtualization.
* Knowledge on installing Red Hat Advanced Cluster Management (RHACM) operator

== Objectives

The overall objectives of this course include:

* Provision the base infrastructure (HW, Storage, Networking) for the hands-on lab environment.
* Install utility services needed for the hands-on labs.
* Configure the base OpenShift infrastructure cluster to host tenant clusters.
* Configure the Infrastructure Cluster to host Virtual Machines.
* Provision multiple tenant clusters on top of the infrastructure cluster.
* Deploy and configure applications and Virtual Machines on Tenant Clusters.
* Test the high availability and resilience of deployed workloads.

== References

https://www.redhat.com/architect/portfolio/detail/51-mission-critical-platform[Red Hat Architecture Center - Mission Critical Application Platform,window=read-later]

https://www.redhat.com/en/blog/building-mission-critical-application-platform[Building a mission critical application platform,window=read-later]

https://github.com/arvin-a/openshift-upi-automation.git[Github - openshift-upi-automation,window=read-later]

https://www.redhat.com/en/blog/nested-openshift-using-openshift-virtualization[Nested OpenShift using OpenShift Virtualization,window=read-later]
