= Deploy Mission Critical Application Platform (MCAP)
:navtitle: Home

Welcome to this quick course, _Deploy Mission Critical Application Platform (MCAP)_.
This course will help you learn the basic infrastructure required for Red Hat MCAP and how to deploy nested OpenShift using OpenShift Virtualization.
After completing this course, you will be able to deploy the MCAP solution for production environments.

Duration: 6 hours, 30 minutes

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Arvin Amirian
* Ricardo Garcia Cavero
* Sarvesh Pandit
* Ashish Shah
* Annie Purcell

== Classroom Environment

=== Red Hat Associates and Partners

Find a bare metal server with at least the following specifications:

. Cores - 32 cores @ 2.3 GHz
. Memory - 512 GB memory
. Storage - 2 x 3.84 TB NVMe

Click https://deploy.equinix.com/product/servers/n3-xlarge/[here,window=read-later] to view the system configuration used to build the lab for this training.

You may need to tweak the automation scripts provided in this training.

== Prerequisites

For this course, you should have:

* Red Hat Certified Systems Administrator certification, or equivalent knowledge of Linux system administration is recommended for all roles.
* https://rol.redhat.com/rol/app/courses/do280-4.14[Red Hat OpenShift Administration II: Configuring a Production Cluster (DO280),window=read-later], or equivalent knowledge on configuring a production Red Hat OpenShift cluster.
* https://rol.redhat.com/rol/app/technical-overview/do016-4.14[Red Hat OpenShift Virtualization (OCP Virt) Technical Overview (DO016),window=read-later]
* https://rol.redhat.com/rol/app/courses/do316-4.14[Managing Virtual Machines with Red Hat OpenShift Virtualization (DO316),window=read-later], or equivalent knowledge on how to create virtual machines on Red Hat OpenShift cluster using Red Hat OpenShift Virtualization.
* Knowledge of installing Red Hat Advanced Cluster Management (RHACM) operator

== Objectives

The overall objectives of this course include:

* Provision the base infrastructure (HW, Storage, Networking) for the hands-on lab environment.
* Install utility services needed for the hands-on labs.
* Configure the base OpenShift infrastructure cluster to host tenant clusters.
* Configure the Infrastructure Cluster to host Virtual Machines.
* Provision multiple tenant clusters on top of the infrastructure cluster.
* Deploy and configure applications and Virtual Machines on Tenant Clusters.
* Test the high availability and resilience of deployed workloads.

== References

https://www.redhat.com/architect/portfolio/detail/51-mission-critical-platform[Red Hat Architecture Center - Mission Critical Application Platform,window=read-later]

https://www.redhat.com/en/blog/building-mission-critical-application-platform[Building a mission critical application platform,window=read-later]

https://github.com/arvin-a/openshift-upi-automation.git[Github - openshift-upi-automation,window=read-later]

https://www.redhat.com/en/blog/nested-openshift-using-openshift-virtualization[Nested OpenShift using OpenShift Virtualization,window=read-later]
