---
- name: Create an ssh key for the root user
  ansible.builtin.shell: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''

- name: Install required packages on hypervisor
  ansible.builtin.dnf:
    name: "{{ packages_hypervisor }}"
    state: latest

- name: Create swap partition on nvme disk in hypervisor
  include_tasks: ./swap.yaml

- name: Create backend LV for ceph storage using nvme disks from hypervisor
  include_tasks: ./lvm.yaml

- name: Enable libvirt and cockpit services on hypervisor
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirt-guests
    - libvirtd
    - cockpit.socket

- name: Configure dhcp server on hypervisor
  include_tasks: ./dhcpd.yaml

- name: Configure dns server on hypervisor
  include_tasks: ./dns.yaml

- name: Configure http server on hypervisor
  include_tasks: ./httpd.yaml

