- hosts: localhost
  become: yes
  vars_files: host_vars/hypervisor
  tasks:
    - name: Prepare hypervisor
      include_tasks: ./initial-setup-hypervisor.yaml

    #- name: Create VMs on hypervisor
    #  include_tasks: ./vms-hypervisor.yaml

    #- name: Deploy ceph storage on storage VM
    #  include_tasks: ./deploy-ceph-storage.yaml
