---
- name: swapoff on hypervisor
  ansible.builtin.shell: swapoff -a

- name: Disable existing swap partition
  ansible.builtin.shell: sed -i '/swap/d' /etc/fstab

- name: Find the used 250GB nvme disk
  ansible.builtin.shell: blkid | awk '{print $1}' | tr -d ':' |  sed 's/\/dev//g' | sed 's/\///g' | awk 'NR==1' | cut -c 1-5
  register: nvme_id

- name: Configure 250GB nvme disk for usage as swap space
  block:
    - name: Run mkswap on disk
      ansible.builtin.shell: mkswap /dev/nvme1n1

    - name: Get UUID of the swap partition
      ansible.builtin.shell: blkid /dev/nvme1n1 | awk '{print $2}' | tr -d '"'
      register: swap_uuid

    - name: Update /etc/fstab entry
      ansible.builtin.shell: echo "{{ swap_uuid.stdout }}	none	swap	none	0	0" >> /etc/fstab
  when: nvme_id.stdout == "nvme0"

- name: Configure 250GB nvme disk for usage as swap space
  block:
    - name: Run mkswap on disk
      ansible.builtin.shell: mkswap /dev/nvme0n1

    - name: Get UUID of the swap partition
      ansible.builtin.shell: blkid /dev/nvme0n1 | awk '{print $2}' | tr -d '"'
      register: swap_uuid

    - name: Update /etc/fstab entry
      ansible.builtin.shell: echo "{{ swap_uuid.stdout }}	none	swap	none	0	0" >> /etc/fstab
  when: nvme_id.stdout == "nvme1"

- name: swapon on hypervisor
  ansible.builtin.shell: swapon -a
