---
- name: swapoff on hypervisor
  ansible.builtin.shell: swapoff -a

- name: Disable existing swap partition
  ansible.builtin.shell: sed -i '/swap/d' /etc/fstab

- name: Configure 250GB nvme disk for usage as swap space
  ansible.builtin.shell: mkswap /dev/nvme1n1 > /tmp/swap.txt

- name: Get UUID of the swap partition
  ansible.builtin.shell: cat swap.txt | grep -i UUID | awk '{print $3}'
  register: swap_uuid

- name: Update /etc/fstab entry
  ansible.builtin.shell: echo "{{ swap_uuid }}	none	swap	none	0	0" >> /etc/fstab

- name: swapon on hypervisor
  ansible.builtin.shell: swapon -a