---
- name: Define a new storage pool
  community.libvirt.virt_pool:
    command: define
    name: images
    xml: '{{ lookup("template", "templates/storagepool.xml.j2") }}'

- name: Build a storage pool if it does not exist
  community.libvirt.virt_pool:
    command: build
    name: images

- name: Start a storage pool
  community.libvirt.virt_pool:
    command: create
    name: images

- name: Autostart a storage pool
  community.libvirt.virt_pool:
    autostart: yes
    name: images

- name: Change qemu file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ base_qcow }}"
    owner: qemu
    group: qemu
    mode: '0644'

- name: Create base QEMU image at the desired size
  ansible.builtin.shell: "qemu-img create -f qcow2 -o preallocation=metadata,cluster_size=2M {{ resized_base_qcow }} {{ resized_base_qcow_disk_size }}"

- name: Use base RHCOS image and resize it to the new QEMU image
  ansible.builtin.shell: "virt-resize --quiet --expand /dev/sda4 {{ base_qcow }} {{ resized_base_qcow }}"


#- name: Define Hub from xml and set autostart
#  community.libvirt.virt:
#    command: define
#    xml: '{{ lookup("template", "templates/hub.xml.j2") }}'
#    autostart: true