---
- name: Define a new storage pool
  community.libvirt.virt_pool:
    command: define
    name: images
    xml: '{{ lookup("template", "templates/storagepool.xml.j2") }}'

- name: Build a storage pool if it does not exist
  community.libvirt.virt_pool:
    command: build
    name: images

- name: Start a storage pool
  community.libvirt.virt_pool:
    command: create
    name: images
